### PR TITLE
Rewrite tests and restructure code

### PR DESCRIPTION
**Pull request by trojczak**
Signed-off-by: Rafał Trójczak <Rafal.Trojczak@makolab.com>

### CODE REVIEW

**Comment by mereolog** [comment]
This does not build on my PC.

**Context:**
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Program Files\apache-maven-3.8.1\bin\..
Java version: 16.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-16.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

**Error:**
[ERROR] Failed to execute goal on project rdf-toolkit: Could not resolve dependencies for project org.edmcouncil:rdf-toolkit:jar:1.11.0: Failed to collect dependencies at info.aduna.commons:aduna-commons-io:jar:2.10.0: Failed to read artifact descriptor for info.aduna.commons:aduna-commons-io:jar:2.10.0: Could not transfer artifact info.aduna.commons:aduna-commons-io:pom:2.10.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [my-grid-repository (http://www.mygrid.org.uk/maven/repository/, default, releases+snapshots)] -> [Help 1]

**Comment by mereolog** [comment]
Serialisation looks fine, though.

**Comment by trojczak** [comment]
@mereolog I've removed the troubling dependency from the project. Now, you should be able to build the project locally. Please let me know. 

Side note: I've squashed commits in order not to have a mess in the Git logs history. You will probably need to forcibly pull the branch.

**Comment by mereolog** [comment]
I got these errors during build:

`[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   SortedJsonLdWriterTest.shouldBeAbleToProduceSortedJsonLdFilePreferringBaseIriOverPrefix:387 base IRI preference file has encoding problem (1) ==> expected: <true> but was: <false>
[ERROR]   SortedJsonLdWriterTest.shouldBeAbleToProduceSortedJsonLdFilePreferringPrefixOverBaseIri:342 prefix preference file has encoding problem (1) ==> expected: <true> but was: <false>
[ERROR]   SortedRdfXmlWriterTest.shouldBeAbleToProduceSortedRdfXmlFilePreferringBaseIriOverPrefix:352 base IRI preference file has encoding problem (1) ==> expected: <true> but was: <false>
[ERROR]   SortedRdfXmlWriterTest.shouldBeAbleToProduceSortedRdfXmlFilePreferringPrefixOverBaseIri:317 prefix preference file has encoding problem (1) ==> expected: <true> but was: <false>
[ERROR]   SortedRdfXmlWriterTest.shouldNotAddOrLoseRdfTriplesWhenWritingInRdfXmlFormatWithBlankNodesMultipleFiles:778 file mismatch between outputDir1 and outputDir2: turtle-example-22_ibn2.rdf ==> expected: <true> but was: <false>
[ERROR]   SortedTurtleWriterTest.shouldBeAbleToProduceSortedTurtleFilePreferringBaseIriOverPrefix:382 base IRI preference file has encoding problem (1) ==> expected: <true> but was: <false>
[ERROR]   SortedTurtleWriterTest.shouldBeAbleToProduceSortedTurtleFilePreferringPrefixOverBaseIri:339 prefix preference file has encoding problem (1) ==> expected: <true> but was: <false>
[ERROR] Errors:
[ERROR]   SortedJsonLdWriterTest.shouldBeAbleToReadVariousRdfDocumentsAndWriteThemInJsonLdFormat:129 » RDFParse
[ERROR]   SortedRdfXmlWriterTest.shouldBeAbleToReadVariousRdfDocumentsAndWriteThemInRdfXmlFormat:138 » RDFParse
[ERROR]   SortedTurtleWriterTest.shouldBeAbleToReadVariousRdfDocumentsAndWriteThemInTurtleFormat:136 » RDFParse
[INFO]
[ERROR] Tests run: 69, Failures: 7, Errors: 3, Skipped: 2`

@trojczak should we worry about them?

**Comment by trojczak** [comment]
@mereolog This means that the tests that are passing on my machine are not passing (for some reasons) on your machine. That's not good. But it is hard for me do any kind of debugging as it works on my machine.

Could you please let me know yours:
- OS,
- Java version,
- Maven version,
- kind of command line tool (Bash, Git-bash, Power Shell etc.)?

By the way, when building, you can omit tests with `-DskipTests` option, e.g.:

mvn clean package -DskipTests

But this is not a solution, obviously.

**Comment by mereolog** [comment]
@trojczak Here it is:
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\Program Files\apache-maven-3.8.1\bin\..
Java version: 16.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-16.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2016", version: "10.0", arch: "amd64", family: "windows"

I am running 'mvn package' from within Command Prompt.

**Review by przemekgradzki — APPROVED** [review]

**Pull request merged**
